### ISSUE TITLE
Repeated execution fails..

### ISSUE THREAD

**Issue by deepesh-agarwal** [crleblanc/PyIrToy#2]
Executing the below code using  `python sendir.py` works, but using the same command again fails, if IRToy is unplugged and re-plugged it works again.  

`````` python
import serial
import irtoy

with serial.Serial('/dev/ttyACM0') as serialDevice:

    # create a new instance of the IrToy class
    toy = irtoy.IrToy(serialDevice)

    irCode = [0, 122, 0, 44, 0, 19, 0, 22, 0, 18, 0, 22, 0, 18, 0, 43, 0, 18, 0, 42, 0, 39, 0, 25, 0, 17, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 38, 0, 24, 0, 17, 0, 43, 0, 19, 22, 213, 0, 121, 0, 44, 0, 19, 0, 22, 0, 18, 0, 22, 0, 18, 0, 43, 0, 18, 0, 43, 0, 38, 0, 24, 0, 17, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 38, 0, 24, 0, 17, 0, 44, 0, 18, 255, 255]
    toy.transmit(irCode)
    irCode = [0, 122, 0, 43, 0, 19, 0, 22, 0, 18, 0, 22, 0, 18, 0, 42, 0, 20, 0, 42, 0, 39, 0, 23, 0, 18, 0, 23, 0, 18, 0, 22, 0, 19, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 0, 18, 0, 23, 255, 255]
    toy.transmit(irCode)
    irCode = [0, 124, 0, 41, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 41, 0, 20, 0, 41, 0, 41, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 19, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 19, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 41, 0, 42, 0, 41, 22, 232, 0, 124, 0, 41, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 41, 0, 20, 0, 41, 0, 41, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 255, 255]
    toy.transmit(irCode)
    irCode = [0, 124, 0, 41, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 41, 0, 20, 0, 41, 0, 41, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 19, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 19, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 41, 0, 42, 0, 41, 22, 232, 0, 124, 0, 41, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 41, 0, 20, 0, 41, 0, 41, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 0, 21, 0, 20, 255, 255]
    toy.transmit(irCode)```
``````

**Comment by cncook001** [comment]
You may want to take a look at this firmware version: http://dangerousprototypes.com/forum/viewtopic.php?f=29&t=7457&p=62279&hilit=lirc#p62279

Fixed overflow bug in Sample mode in Firmware 2.4

**Comment by crleblanc** [comment]
Thanks, that sounds promising.  I'll have a look.

**Comment by crleblanc** [comment]
It's been a busy month.  I upgraded my IR toy to version 2.4 and tried a simple pyirtoy script that was repeatedly transmitting an IR signal.  Qualitatively it seems more robust than before, but unfortunately it has still entered the bootloader at some point while running overnight.  I'll keep experimenting but I have a feeling there could be more bugs in the firmware.

**Comment by cncook001** [comment]
Something else to review: https://sourceforge.net/u/bengtmartensson/lirc/ci/experimental-irtoy/

**Comment by Saijin-Naib** [comment]
Chris,

Any chance you could/would take another look at this code and merge master with nohs and nogc?

Let's throw everything we can at the irtoy to hopefully keep it running a while stably :P.

**Comment by crleblanc** [comment]
I could be mistaken but my impression is that the IR Toy project is dead.  The firmware hasn't been updated for several years.  It's hard to say without more in-depth debugging of the IR Toy but it seems like buggy firmware.  This isn't something that can be fixed by this Python package.  I tried both the no-handshake and no-gc workarounds but they didn't help.

I gave up on the IR Toy several years ago.  My use case was controlling an air conditioner.  I decided to buy a commercial product (the Sensibo) to do what I was doing with the IR Toy and a raspberry pi.  It's the lazy way out but it's been virtually hassle free.

I'd be happy to accept a pull request if you find a robust solution to this problem but I suspect this isn't possible without a fix to the buggy firmware.

Have you investigated using a Arduino for this task?  A friend of mine had much more success with that approach.  If you prefer Python the Pyboard might be an option: http://micropython.org/.  There's probably other options but I haven't looked recently.

Closing this issue.

**Comment by Saijin-Naib** [comment]
I have much the same impression that it has been abandoned (sadly).

Yes, I found your work when working on controlling my frog's tank. In fact, you assisted me greatly in getting my code running. Glad to hear your project is going quite well :)

I still don't know how to do a PR, but I finally have a GitHub account (I didn't when you were helping me). I'm curious if merging all your commits into one amalgamated branch would improve things any. I can usually get just under a month of stable running on my IRToy with pretty heavy usage (sending at least one signal per hour 24/7) using the nohs branch, so my naïve thought is that combined with nogc might net me a bit more runtime.

No, but you did recommend me the Micropython board. That may have to be my ultimate destination, but I'm not ready to jump ship quite yet.

Thanks for all your hard work, regardless.

**Comment by sputnik63** [comment]
Excuse me if I write in a closed issue, and maybe it's not the same problem, but I wrote some code using PyIrToy and it worked. Than I made some changes and suddenly the toy was hanging at first transmission.
This was due to the fact that for some reason I put 255, 255 at the head of my list of codes to transmit.
When I realized this and I removed them all was working again.
Maybe this is a completely different problem or maybe this could help you to understand something more about this issue. I see that in the codes sent by deepesh-agarwal there are no 255,255 at the beginning of each list but maybe the two final 255 on those list, sent so quickly, could "confuse" the toy

P.S. When it hangs, lsusb -v shows 3 item with result "(error)". If I well remember they are iManufacturer, iProduct, iSerial
